### ISSUE TITLE
Grayish colour on text in top panel

### ISSUE THREAD

**Issue by heksesang** [decathorpe/elementary-nightly-rpms#10]
The top panel has a very grayish font which is hard to read. Might be related to the overall theme? Is there a way to set a similar theme to the one in Elementary OS?

**Comment by decathorpe** [comment]
Yes, this is a known (to me and upstream) theming issue. Installing the egtk GTK theme and using it (for example, set it with gnome-tweak-tool (easy) or in dconf-editor(hard)) renders the top panel "correctly" - this might only be a valid option on fedora 23, though, because the elementary GTK theme is not yet compatible with GTK 3.20 in fedora 24 (and won't be for some time).
