### ISSUE TITLE
Lock screen doesn't work in Fedora 23

### ISSUE THREAD

**Issue by heksesang** [decathorpe/elementary-nightly-rpms#13]
When clicking Lock from the power menu or trying any key shortcut that should have locked the computer, nothing happens.

Running Fedora 23, and I have never had this issue in Elementary Freya, so I assume it's a Fedora specific thing.

**Comment by decathorpe** [comment]
This has to do with them using the freedesktop screensaver interface, which seems to not be supported by gdm. Although, after mentioning this problem to the developers, they discussed switching to logind (which is supported on fedora, too), in the future. So this sadly won't fix for gdm on fedora, but might be fixed by an upstream change in the future.
