### ISSUE TITLE
Keyboard Shortcuts not working

### ISSUE THREAD

**Issue by daniel-wtd** [decathorpe/elementary-nightly-rpms#18]
Most of the keyboard-shortcuts are not working, which are known for Pantheon:

Super + Space -> Slingshot Launcher
Super + A -> Show All Windows
Super + W -> Show all Windows on current Desktop
Super + S -> Open Multiwindow Manager

Instead some of the gnome-shortcuts are working like 

Super + Down -> unmaximize/minimize Window

PS: I really, really appreciate your work here :)

**Comment by decathorpe** [comment]
This "oversight" is intentional.

There is no way (I know of) to enforce these keyboard shortcuts for a "secondary" DE, because elementary/pantheon re-uses the gnome gsettings keys there (org.gnome.desktop.wm.keybindings). And overriding them for pantheon also changes keybindings for GNOME - and "breaking" the existing DE is something I won't do.

I mean, you could write a custom shell script that runs at login and changes the keybindings depending on the DE, but that is a bit outside the scope of things I am willing to do for "packaging" :wink:
