### ISSUE TITLE
Refresh schemas on removing

### ISSUE THREAD

**Issue by Obsidien** [decathorpe/elementary-nightly-rpms#32]
On removing of “pantheon-session-settings-overrides,” it would be great to run `glib-compile-schemas` on the system directory, to restore/reapply the previous GSettings defaults.

**Comment by decathorpe** [comment]
That's strange, RPM should automatically run glib-compile-schemas after changes to the /usr/share/glib-2.0/schemas/ directory are detected ...

Does running it manually fix the problem, or is it possible it overrides user settings and previous settings are lost?

As a side note, I strongly advise against installing the -overrides package on a "normal" system exactly because of problems like this one.

**Comment by Obsidien** [comment]
Well, it didn’t, twice. Maybe because it’s an override (isn’t it?), not a new schema? Might need a bugreport elsewhere.

Running `glib-compile-schemas .` in `/usr/share/glib-2.0/schemas/` fixed the problem, yes.

**Comment by decathorpe** [comment]
I have added the scriptlet for the -overrides package to the latest build (in -nightly and -stable). That should fix your issue.

**Comment by Obsidien** [comment]
Works as expected, thanks. :-)
